### ISSUE TITLE
when you change story, related task resets

### ISSUE THREAD

**Issue by vnabatov** [vnabatov/pipl#10]

**Comment by usovdm-wiley** [comment]
How to reproduce it? I couldn't

**Comment by vnabatov** [comment]
easy https://www.dropbox.com/s/c6hcyqzy6pa7gxw/2019-10-04%2015-37-43.mp4?dl=0
Steps: 
**1** Select a task with dependencies
**2** Change a story
AR: dependencies become not selected
ER: dependencies are kept selected

**Comment by usovdm-wiley** [comment]
component react-select-search doesn't work properly. It can't find by multiple (array) value in componentWillReceiveProps and resets to []. Hack with key={JSON.stringify(relatedTasks)} helps only with changes in current select. But component fails when other selects are changing.

**Comment by usovdm-wiley** [comment]
I propose to replace it to react-select

**Comment by vnabatov** [comment]
thanks, let's replace, moved from blocked to ready
